name: Green Day

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 1/4 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Set global directory
        run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update
        run: |
          cat > GREEN_DAY
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > GREEN_DAY

      - name: Commit changes
        run: |
          git config --local user.email "rdjanuar008@gmail.com"
          git config --local user.name "rdjanuar"
          git add -A
          git commit -m "<3"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
